process.on("unhandledRejection", (reason, promise) => {
    console.error("ðŸ’¥ Unhandled Rejection:", reason);
});

process.on("uncaughtException", (err) => {
    console.error("ðŸ’¥ Uncaught Exception:", err);
});
